### ISSUE TITLE
64 bit software?

### ISSUE THREAD

**Issue by borgom7615** [mastercomfig/tf2-patches#579] opened 2021-05-13 17:28 UTC
i don't know anything about anything when it comes to software so this may be impossible....

i have a mac i use for music production and wile i dream for a PC that costs money

I recently found out by a terrible mistake apple no longer supports 32bit software, team fortress 2 is 32bit software

is there a way we can change that?!? make it 64bit compatible? because as it stands, TF2 is no longer technically Apple compatible.

**Comment by melvyn2** [comment] 2021-05-13 18:18
dupe of https://github.com/mastercomfig/team-comtress-2/issues/67

**Closed** 2023-02-16 23:11 UTC
Labels: enhancement, needs triage
